# Generated by Django 3.2.8 on 2022-07-18 06:49

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('tution', '0004_auto_20220717_1950'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='medium',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('bangla', 'bangla'), ('English', 'English'), ('Math', 'Math'), ('Hindi', 'Hindi')], default='bangla', max_length=100),
        ),
    ]
