# Generated by Django 3.2.8 on 2022-07-26 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tution', '0006_auto_20220721_1729'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.CharField(choices=[('Teacher', 'Teacher'), ('Student', 'Student')], max_length=100),
        ),
        migrations.AlterField(
            model_name='post',
            name='subject',
            field=models.ManyToManyField(related_name='subject_name', to='tution.Subject'),
        ),
    ]
