# Generated by Django 3.2.8 on 2022-08-19 04:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tution', '0007_auto_20220726_1954'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='class_in',
            new_name='Class_in',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='subject',
            new_name='Subject',
        ),
    ]
