# Generated by Django 3.2.8 on 2022-10-03 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('session', '0004_alter_userprofile_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='blood_group',
            field=models.CharField(choices=[('A-', 'A-'), ('AB+', 'AB+'), ('A+', 'A+')], max_length=3),
        ),
    ]
